export const workoutGifs = [
  {
    id: "pushups",
    name: "Push-ups",
    gifUrl: "/workouts/pushups.json",
    description: "Great for chest, shoulders, and triceps",
    isLottie: true,
  },
  {
    id: "squats",
    name: "Free Squats",
    gifUrl: "/workouts/squats.json",
    description: "Works your quads, hamstrings, and glutes",
    isLottie: true,
  },
  {
    id: "hip",
    name: "Free Single Leg Hip",
    gifUrl: "/workouts/hip.json",
    description: "Targets your glutes and core",
    isLottie: true,
  },
  {
    id: "jumping-jacks",
    name: "Jumping Jacks",
    gifUrl: "/workouts/jumping-jacks.json",
    description: "Great cardio exercise",
    isLottie: true,
  },
  {
    id: "plank",
    name: "Plank",
    gifUrl: "/workouts/plank.json",
    description: "Strengthens your core and improves posture",
    isLottie: true,
  },
  {
    id: "stretch",
    name: "Free Forearm Stretch",
    gifUrl: "/workouts/stretch.json",
    description: "For your forearms",
    isLottie: true,
  },
  {
    id: "burpees",
    name: "Burpees",
    gifUrl: "/workouts/burpees.json",
    description: "High-intensity full body exercise",
    isLottie: true,
  },
];
